name: Check for unused files
on:
  push:
    branches:
      - "master"

jobs:
  check_files_warning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ZimboPro/flutter-unused-files@v1.0.3
        with:
          warning: true
  check_files_ignore_assets:
    runs-on: ubuntu-latest
    needs: [check_files_warning]
    steps:
      - uses: actions/checkout@v3
      - uses: ZimboPro/flutter-unused-files@v1.0.3
        with:
          assets: true
  check_files:
    runs-on: ubuntu-latest
    needs: [check_files_ignore_assets]
    steps:
      - uses: actions/checkout@v3
      - uses: ZimboPro/flutter-unused-files@v1.0.3
        with:
          assets: true
